/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorContarctSol from "./GovernorContarct.sol";
export { TimeLock__factory } from "./TimeLock__factory";
