/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorContarctSol from "./GovernorContarct.sol";
export type { governorContarctSol };
export type { TimeLock } from "./TimeLock";
